### ISSUE TITLE
Need an option to select multiple items/rows.

### ISSUE THREAD

**Issue by snep** [chenzeyu/CZPicker#1]
Hi Chenzeyu, Love the work and effort you have put into this component. It just looks production ready and you seem to have put in lots of thought into making it customizable. I have one minor request to allow selection of multiple rows.

Thanks

**Comment by chenzeyu** [comment]
Hi snep, will add the feature in the near future, thanks for your comment.

**Comment by chenzeyu** [comment]
Added multiple selection support at 0ad9bc9a17b9a8776c35617c782898233296e2ac
