### ISSUE TITLE
Option to provide pre-selected items

### ISSUE THREAD

**Issue by nitinhayaran** [chenzeyu/CZPicker#15]
Currently there is no way to provide pre-selected items. 

Possible use case:
If we save selected options on backend, then ideally Picker should be loaded with pre-selected options.

**Comment by chenzeyu** [comment]
I think I figured out how to do it properly, will add soon.

**Comment by chenzeyu** [comment]
added ```- (void)setSelectedRows: (NSArray *)rows;``` in 0.3.6
