### ISSUE TITLE
can't appear!

### ISSUE THREAD

**Issue by lhyhsx** [chenzeyu/CZPicker#16]
appear error when run below code:
![1](https://cloud.githubusercontent.com/assets/9956247/9872486/380084ac-5bcc-11e5-8233-e4cafe37dc8d.png)

error:
![2](https://cloud.githubusercontent.com/assets/9956247/9872487/397de482-5bcc-11e5-9231-d4dee8c1bbc0.png)

**Comment by chenzeyu** [comment]
Currently I ignore the warning because I want the visual effect. Will try to solve it later.
