### ISSUE TITLE
Implement two or more CZPicker?

### ISSUE THREAD

**Issue by subhash08** [chenzeyu/CZPicker#17]
How can i implement two or more picker with deferent arrays in same viewController

**Comment by chenzeyu** [comment]
all delegate methods gives the reference to the picker, e.g. ```- (NSString *)czpickerView:(CZPickerView *)pickerView  titleForRow:(NSInteger)row;```, you can have different pickers and use ```pickerView``` in delegate method to find out which picker is the one you want.

**Comment by subhash08** [comment]
it shows duplicate declaration error

**Comment by chenzeyu** [comment]
Can you post your code somewhere?

**Comment by subhash08** [comment]
can i post code here ?

**Comment by chenzeyu** [comment]
sure, please

**Comment by subhash08** [comment]
source array:

     self->citys = @[@"Jaipur",@"Kota",@"Alwar",@"Dausa",@"Udaipur",@"Jisalmair",@"Jodhpur",@"Ajmer",@"Tonk",@"Jaipur",@"Kota",@"Alwar",@"Dausa",@"Udaipur",@"Jisalmair",@"Jodhpur",@"Ajmer",@"Tonk"];
        self->room = @[@"Meeting",@"Confrence",@"Brain Storming"];
 my code in viewController
       
     - (NSAttributedString *)czpickerView:(CZPickerView *)pickerView
               attributedTitleForRow:(NSInteger)row{
    
    NSAttributedString *att = [[NSAttributedString alloc]
                               initWithString:self->citys[row]
                               attributes:@{
                                            NSFontAttributeName:[UIFont fontWithName:@"Avenir-Light" size:18.0]
                                            }];
    return att;
    
      }

    - (NSString *)czpickerView:(CZPickerView *)pickerView
               titleForRow:(NSInteger)row{
        return self->citys[row];
        }

    - (NSInteger)numberOfRowsInPickerView:(CZPickerView *)pickerView{
          return self->citys.count;
            }

     - (void)czpickerView:(CZPickerView *)pickerView didConfirmWithItemAtRow:(NSInteger)row{
         NSLog(@"%@ is chosen!", self->citys[row]);
           self->cityTxt.text = self->citys[row];
          }



        - (void)czpickerViewDidClickCancelButton:(CZPickerView *)pickerView{
               NSLog(@"Canceled.");
          }
        - (void)showPicker {
              CZPickerView *picker = [[CZPickerView alloc] initWithHeaderTitle:@"Location"                                           cancelButtonTitle:@"Cancel" confirmButtonTitle:@"Confirm"];
    picker.delegate = self;
    picker.dataSource = self;
    picker.needFooterView = YES;
    [picker show];
      }

its works fine but when I try to implement it second time it shows error of duplicate declaration.

**Comment by subhash08** [comment]
have any solution??

**Comment by mythodeia** [comment]
@subhash08 you do not implement the same methods again. you use the pickerView reference to get the correct instance you want

**Comment by subhash08** [comment]
how can i do it ? can you please explain more.

**Comment by mythodeia** [comment]
init 2 instances of your pickers
both pickers will respond to the same methods above. 
you can distinguish between them using the pickerView reference of the method e.g
in method: ``` - (NSAttributedString *)czpickerView:(CZPickerView *)pickerView```
use the ```pickerView``` reference to check which instance is it you want.
to work you need to instantiate more than 1 picker in your class

**Comment by subhash08** [comment]
actuly I'm not getting you, sorry for that.

**Comment by chenzeyu** [comment]
@mythodeia thanks for you explanation.
@subhash08 you can use the following code to distinguish the pickers:

```
- (NSString *)czpickerView:(CZPickerView *)pickerView titleForRow:(NSInteger)row{
    if ([self.pickerOne isEqual: pickerView]){
            // return pickerOne's titles
    } else if ([self.pickerTwo isEqual: pickerView]{
            // return pickerTwo's titles
    }
}
```

The delegate methods are the same as UITableViewDelegate methods, if you have 2 tableviews, you need to figure out which one is which.

**Comment by mythodeia** [comment]
:+1:

**Comment by chenzeyu** [comment]
I'm closing this issue because it is not related to this project.

**Comment by subhash08** [comment]
done .. thanks @chenzeyu your idea help me to do it .
