### ISSUE TITLE
How to Change the width of the Picker in iPad ?

### ISSUE THREAD

**Issue by AruLNadhaN** [chenzeyu/CZPicker#18]
The Current picker looks like this http://i.imgur.com/8ukAmno.png. So i Need to change the Width of the Picker. How can i Achieve this ?

**Comment by chenzeyu** [comment]
@AruLNadhaN currently there's no way to customize the width of picker, will add soon.

**Comment by ChekistNSK** [comment]
U should modify CZPickerView.m file.

Add:
#define FRAME_WIDTH 300.0

And modify:
1) self.containerView.frame = CGRectMake(frame.origin.x,
                                          frame.origin.y,
                                          FRAME_WIDTH,
                                          self.headerView.frame.size.height + self.tableView.frame.size.height + self.footerview.frame.size.height);
2) tableRect = CGRectMake(0, 44.0, FRAME_WIDTH, height);
3) tableRect = CGRectMake(0, 44.0, FRAME_WIDTH, newRect.size.height - heightOffset);

**Comment by chenzeyu** [comment]
@ChekistNSK thanks for your answer.

**Comment by chenzeyu** [comment]
added ```pickerWidth``` in v0.4.0.
