### ISSUE TITLE
orientation issue

### ISSUE THREAD

**Issue by mythodeia** [chenzeyu/CZPicker#2]
There is an issue with the orientation of the picker. To simulate do the following:
Open the app in portrait and tap to open the picker.
Then rotate the device. You will see that it does not show correctly.

Thanks for the library.

**Comment by chenzeyu** [comment]
Thanks for your feedback, will fix soon.

**Comment by chenzeyu** [comment]
Solved in version 0.2.1 5dc193313c25151ba12394e0bb11f9faf60c4c0b.

**Comment by mythodeia** [comment]
thanks :+1:
