### ISSUE TITLE
Reselecting the same row causes the selectedRows() method to return an empty array

### ISSUE THREAD

**Issue by crowdless-app** [chenzeyu/CZPicker#23]

**Comment by crowdless-app** [comment]
Actually thinking about it, this might be intended. Is there an option for making sure that some row is always selected?

**Comment by chenzeyu** [comment]
@crowdless-app , yup that's the intended way, it is natural to allow user unselect items right? I do not have a plan to add such an option right now, please feel free to fork it and add your own methods.

**Comment by crowdless-app** [comment]
I'm using the picker for a table sort, so an option always needs to be selected. However, it was easy to just check if the number of selected rows == 0 in the delegate method that is called when a user selection occurs and set the selected row back to what it was before.  Thanks though.
