### ISSUE TITLE
Support clear background view

### ISSUE THREAD

**Issue by Oggerschummer** [chenzeyu/CZPicker#27]
Currently the picker is dimming the background to a very dark grey.
From usability perspective I always prefer to have the screen from which the picker is called to be visible.
Having a dimmed background without the application screen visible breaks the  visual flow of an application - pickers should just pop up and vanish from my perspective.

An change to have a switch allowing to disable the dimming / colouring of the view - ideally completely removing it but keeping the cancel functionality when clicking outside of he picker list alive ?.

Perfect solution would be to be able to present the picker from a control (rect) , just showing it as a popup instead of  a modal view.

**Comment by chenzeyu** [comment]
@Oggerschummer My intention to have a dimming background when the picker is showing is to draw users' attention to the picker, I was trying to mimic the way a UIAlertView's style.

However I do agree it's good to let developers have more options. I will add such a switch.

As for the better solution you proposed, can you elaborate more on that idea?
