### ISSUE TITLE
Sometimes the menu pops up multiple times

### ISSUE THREAD

**Issue by StainlessStlRat** [chenzeyu/CZPicker#32]
Anyone else seen this? Know how to deal with it?

**Comment by chenzeyu** [comment]
@StainlessStlRat  Can you post your code?

**Comment by StainlessStlRat** [comment]
Sure, it's pretty small in terms of initialization.  I can send you my delegate class too.

Here is an example:

_czPlatformPickerDelegate = [[CZPlatformPickerViewDelegate alloc] init];
    _czPlatformPickerDelegate.delegate = self;
    _czPlatformPickerDelegate.platformPickerType = PlatformPickerTypes_ByComputer;
    _czPlatformPickerDelegate.settings = _settings;
    
    CZPickerView *picker = [[CZPickerView alloc] initWithHeaderTitle:@"Select a Computer"
                                                   cancelButtonTitle:@"Cancel"
                                                  confirmButtonTitle:@"Confirm"];
    
    picker.headerBackgroundColor = [UserSettings gameyeThemeColor];
    picker.delegate = _czPlatformPickerDelegate;
    picker.dataSource = _czPlatformPickerDelegate;

**Comment by chenzeyu** [comment]
is it possible that your button which triggers the picker was tapped twice? I don't see anything wrong with your code and I haven't experienced/reported multiple pop ups before.

**Comment by StainlessStlRat** [comment]
I thought that might be the case so I protected everything to make sure it never relaunches an instance and it still seems to happen occasionally. Especially if the menu is left open when returning from background.

**Comment by chenzeyu** [comment]
I'll take a look.

**Comment by StainlessStlRat** [comment]
I have some more information!  It looks like the reload happens whenever I go from the phone laying flat (like on a table) to picking it up where the phone is perpendicular with the ground.  Everytime I change from those two positions the menu reloads.

**Comment by chenzeyu** [comment]
@StainlessStlRat You mean you're changing the orientation of device? Yes then it dose relaunch to fit in new width & height, however it preserves the selections users made earlier, so it should be fine.

**Comment by StainlessStlRat** [comment]
Hi Chenzeyu, the orientation is not changing from landscape to portrait or anything like that.  Just simple the difference between it laying flat on it's back and it being picked up and being held to the user's face.

**Comment by StainlessStlRat** [comment]
I see the orientation change you are mentioning, that seems to work just fine.  But this is basically just picking up the device from flat on it's back to going to where it's lightening port is pointing at the ground

**Comment by StainlessStlRat** [comment]
Sorry if I am not able to describe it perfectly!

**Comment by chenzeyu** [comment]
I see, let me investigate, thanks!

**Comment by chenzeyu** [comment]
It actually a bug. Due to my oversight, czpicker does not handle FaceDown & FaceUp orientation, so if the device was on table(FaceUp or FaceDown) and was picked up(Portrait or landscape), the animation pops, because it is a orientation change.

This bug is fixed in 0.4.2, now czpicker checks screen size to determine if animation is needed.

**Comment by StainlessStlRat** [comment]
Awesome!
