### ISSUE TITLE
how to add an optional search bar.!

### ISSUE THREAD

**Issue by kunalverma25** [chenzeyu/CZPicker#33]
With an optional search bar on top of the the table view, the CZPicker will be optimized for using in large lists. I currently use it with lists having 10-200 items. and It will be awesome if it will be supported in a later version.

**Comment by chenzeyu** [comment]
I think it's a good idea. I will test it out. My major concern is that with keyboard appears, the picker size may not fit screen.

**Comment by kunalverma25** [comment]
Yes that might me a concern. But you can allow the keyboard to end editing when return is pressed. revealing the picker with filtered results.

**Comment by chenzeyu** [comment]
I think this picker should be kept simple. If there're too many items, say 200. It's better do use a new ViewController in the way how Apple did in Contacts.
