### ISSUE TITLE
Unable to use didConfirmWithItemsAtRows for selecting multiple items

### ISSUE THREAD

**Issue by astuter** [chenzeyu/CZPicker#34]
I want to let use select multiple item in my PickerView. 

`func czpickerView(pickerView: CZPickerView!, didConfirmWithItemsAtRows rows: Array!) {
 }`

If I use delegate method as above, I am getting both warning and error as shown in below image:

![error](https://cloud.githubusercontent.com/assets/12004314/14559803/e331a21c-0328-11e6-9b94-c4aa1b8222de.png)

Changing method to following remvoes the warning but error is still there:
`@objc func czpickerView(pickerView: CZPickerView!, didConfirmWithItemsAtRows rows: Array) { }` 

What I'm missing for this method?

**Comment by chenzeyu** [comment]
let me test out.

**Comment by chenzeyu** [comment]
@astuter if you integrate CZPicker using cocoapods in a Swift project, you can click into the ```CZPickerViewDelegate``` header file, where the content is as follows:
```swift
public protocol CZPickerViewDelegate : NSObjectProtocol {
    
    /** delegate method for picking one item */
    optional public func czpickerView(pickerView: CZPickerView!, didConfirmWithItemAtRow row: Int)
    
    /*
     delegate method for picking multiple items,
     implement this method if allowMultipleSelection is YES,
     rows is an array of NSNumbers
     */
    optional public func czpickerView(pickerView: CZPickerView!, didConfirmWithItemsAtRows rows: [AnyObject]!)
    
    /** delegate method for canceling */
    optional public func czpickerViewDidClickCancelButton(pickerView: CZPickerView!)
}
```

Therefore, you should use ```[AnyObject]!1``` instead of ```Array```. I just created a swift demo, you can refer to that project.

**Comment by astuter** [comment]
@chenzeyu :+1: Thanks yes that helped !
