### ISSUE TITLE
Checkmark is not cleared when cancel is pressed.

### ISSUE THREAD

**Issue by kunalverma25** [chenzeyu/CZPicker#35]
If I select a cell, and presses enter, and the open the popup again, the checkmark is still there.
Just a bug there..

**Comment by chenzeyu** [comment]
It's intended, because the picker instance was not destroyed and gets reused.
You have two options, 1. init a new czpicker instance, 2. clear selected rows, you can refer to CZPickerView.h to find how to set selected rows.
