### ISSUE TITLE
handle event where user hits the confirm button without selecting row

### ISSUE THREAD

**Issue by mac8878** [chenzeyu/CZPicker#36]
can we handle the event where user hits the confirm button without selecting anything from row  ??

**Comment by chenzeyu** [comment]
Hi @mac8878 , there's no way to do it now, I think a pickerWillDismiss delegate method will do.

**Comment by chenzeyu** [comment]
in 0.4.3, several new delegate methods have been added. You now can know when the picker was dismissing. So you can tell if user has selected anything.

**Comment by pdgoyal** [comment]
Can you provide example for this?
