### ISSUE TITLE
set maximum number of items

### ISSUE THREAD

**Issue by omar14** [chenzeyu/CZPicker#37]
Hi, Thanks for the great picker

I want to set a maximum number of items that the user can select and display a message when he select an item and reach the max.

For now I'm handling this through didConfirmWithRows and show the picker again if the max is reached/exceeded, but it would be kind of confusing since you have to go through the whole list again to unselect.

Is there a way or a delegate method that I missed that can do this ?

Thanks.

**Comment by chenzeyu** [comment]
Hi @omar14 , currently there's no way to set maximum number of items.
In multiple selection mode, the delegate method gets called only after confirm button is clicked.
A workaround can be if the user has selected more items than desired, you just re-pop the picker.

Another way is to observe the changes to ```selectedIndexPaths``` property, which is currently private, you will have to do it yourself.

**Comment by chenzeyu** [comment]
Hi @omar14 , currently there's no way to set maximum number of items.
In multiple selection mode, the delegate method gets called only after confirm button is clicked.
A workaround can be if the user has selected more items than desired, you just re-pop the picker.

Another way is to observe the changes to ```selectedIndexPaths``` property, which is currently private, you will have to do it yourself.
