### ISSUE TITLE
Change the data label font type and size

### ISSUE THREAD

**Issue by glennposadas** [chenzeyu/CZPicker#39]
Hi CZ, thanks for this awesome picker. BEST CUSTOM CONTROL FOR PICKER EVER! - 

Anyway, I'd like to request a feature or can you tell me a way to change the label's font type and size? My  strings to be displayed in the picker are quite long.

Thanks.
G

**Comment by chenzeyu** [comment]
Hi, thanks for using this control.

There's a delegate method called ```attributedTitleForRows``` where you can give NSAttributedString to the picker to display, so you can set the font of the labels.
