### ISSUE TITLE
Multiple CZPicker in one ViewController

### ISSUE THREAD

**Issue by getSwiftly** [chenzeyu/CZPicker#44]
Hello, can you help me how to get selected row from 2 different pickerview opened at different times. The didConfirmWithItemsAtRows doesn't invoke.

**Comment by chenzeyu** [comment]
You can keep two instances of the picker inside your viewcontroller.
Please refer to #17 to see solution.

**Comment by getSwiftly** [comment]
Thanks I got it. Had found the way to work it out right after posting.
