### ISSUE TITLE
Non-selectable / greyed out option?

### ISSUE THREAD

**Issue by aravasio** [chenzeyu/CZPicker#50]
Is there a way to set X many rows as non-interactive? Or 'force select/unselect'?

I'm using `setSelectedRows` for passing a few pre-selections I want already ticked. I was wondering if there's a way to make them (or a subset) non-active so the user can't select/unselect them.

**Comment by chenzeyu** [comment]
Hi @aravasio , disabling options is not supported yet, and will not be added in a short while, you can fork the picker and add it yourself.
