### ISSUE TITLE
How to Hide popup automatically when socket refresh 

### ISSUE THREAD

**Issue by KrishnaVenkat1312** [chenzeyu/CZPicker#54]
Hi,

I am showing popup when get some response from socket. But in this scenario i want to hide without touch the popup will close while get another response from socket...  How to do this one.. I tried button cancel action. But its not working.. Kindly help us..

i create this function in CZPickerView.m

- (void)hide {
    [self cancelButtonPressed:self];
    [self buildBackgroundDimmingView];
}

Thans
Krishna

**Comment by chenzeyu** [comment]
Hi, I don't think the current code support such requirement, you can add it your self.
