### ISSUE TITLE
Issue with exporting IPA

### ISSUE THREAD

**Issue by ravifullestop** [chenzeyu/CZPicker#55]
[MT] Presenting: Error Domain=IDEFoundationErrorDomain Code=1 "Info.plist of “App.app/Frameworks/CZPicker.framework” specifies a simulator platform for the CFBundleSupportedPlatforms key" UserInfo={NSLocalizedDescription=Info.plist of “App.app/Frameworks/CZPicker.framework” specifies a simulator platform for the CFBundleSupportedPlatforms key}

**Comment by chenzeyu** [comment]
will this answer be helpful? https://stackoverflow.com/questions/41099723/reactiveobjc-framework-specifies-a-simulator-platform-for-the-cfbundlesupportedp/41112807#41112807

**Comment by ravifullestop** [comment]
This does not work also facing more issue when uploading to app store. 

![screen shot 2017-08-14 at 6 02 47 pm](https://user-images.githubusercontent.com/8253267/29271782-d9604e20-811a-11e7-83e0-45c265a4c5c5.png)

**Comment by ravifullestop** [comment]
Not working :(

Also facing below issues now when uploading to app store.

![screen shot 2017-08-14 at 6 04 03 pm](https://user-images.githubusercontent.com/8253267/29271819-098f9c2c-811b-11e7-8036-67641f70f0a2.png)
