### ISSUE TITLE
Multi Line Text

### ISSUE THREAD

**Issue by MuhammadAhmedBaig** [chenzeyu/CZPicker#57]
When any option have big text then it doesn't show full text and "..." shows at the end.
Is it possible to increase number of lines of picker options?

**Comment by YahyaBagia** [comment]
Hello @MuhammadAhmedBaig. I was facing similar issue and changed a little bit of code in `CZPickerView.m` file and it satisfied my requirements.

Just add new line with following code on `tableView: cellForRowAtIndexPath` method.

`cell.textLabel.numberOfLines = 0;`

And that's it.

![czpicker_change](https://user-images.githubusercontent.com/25579208/32402909-1454238e-c154-11e7-9a60-2879500f7581.png)
