### ISSUE TITLE
How can i add a view on the headerView of the Picker?

### ISSUE THREAD

**Issue by goribchat** [chenzeyu/CZPicker#60]
Hello there is only HeaderTitleFont,HeaderTitleColor. How can i add a view on Header in swift 4?

**Comment by chenzeyu** [comment]
Hi, I think there's no way to do it, I was trying to make it simple when I made it. You can fork it to add headerview, should be fairly straightforward.

**Comment by goribchat** [comment]
Okay Thanks Man
