### ISSUE TITLE
multiple selection not work in swift

### ISSUE THREAD

**Issue by ryamashita** [chenzeyu/CZPicker#65]
Hi, thanks for your work.
I am using Swift 4, and try to use multiple selection.

However, [self.delegate respondsToSelector:@selector(czpickerView:didConfirmWithItemsAtRows:)] is always false and cannot call function "func czpickerView(pickerView: CZPickerView!, didConfirmWithItemsAtRows rows: [AnyObject]!)"

Do you know why?

Thanks.

**Comment by chenzeyu** [comment]
Can you post a sample code here? I used this control yesterday in swift project and it turned out fine.

**Comment by ryamashita** [comment]
Thanks for your message.
I have noticed that 

func czpickerView(pickerView: CZPickerView!, didConfirmWithItemsAtRows rows: [AnyObject]!) {
}
does not work, but

func czpickerView(_ pickerView: CZPickerView!, didConfirmWithItemsAtRows rows: [Any]!) {
}
works.

Anyway thank you for your support.

**Comment by chenzeyu** [comment]
@ryamashita then looks like it's method signature doesn't match, this library is written in Obj-C so have to be careful :D
