### ISSUE TITLE
Orientation Issue

### ISSUE THREAD

**Issue by wanpaya** [chenzeyu/CZPicker#7]
I found an issue about orientation on Portrait app.
I set project configure as Portrait orientation only.
But every times I rotate an app. CZPicker view will animate in again. 

Using CZPicker (0.3.2)

**Comment by chenzeyu** [comment]
Thanks @wanpaya, I noticed this issue as well, will fix soon.

**Comment by chenzeyu** [comment]
Fixed in v0.3.3 0f88484fa34d224e08bc072a24aed872d0b8222c

**Comment by wanpaya** [comment]
Thanks
