### ISSUE TITLE
Need to handle case: selectedIndexPath 

### ISSUE THREAD

**Issue by hoanganh6491** [chenzeyu/CZPicker#9]
First off all i have to say this is very nice popup view (Thank you!)
-
Because of we can use this popup for multiple selection functions in view.
Example: use 1 picker for all case ~
button 1 - handle selection Name
button 2 - handle selection Sex
button 3 - handle selection Locations

IF 
we select option 2 for case of Button 1
then we touch on Button 2 -> selection check mark will be option 2 but we(user) did not do anything

Therefore, i think we should use 1 flag for this checking: should remember last selection or not.

Anyway, we can handle this issue by create multiple picker (but i think it is not good idea enough ~from my self)

:) Thank you! This is really nice popup view.
Sorry if i have some grammar problem.

**Comment by chenzeyu** [comment]
Thanks, I think the picker should clear previous selections when ```show``` is called.

BTW, no worries about your grammar, I am not a native speaker either :P.

**Comment by chenzeyu** [comment]
After thinking through this, I think the best way to solve the problem would be using multiple pickerViews for each field. And there're people asking for an option for getting previously selected items, I see this as a more common need. Therefore this feature would not be added.
